PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX ns1: <http://www.semanticweb.org/sws/group4/ontology/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
select distinct ?country ?s ?lat ?lon where { 
    
    SERVICE <http://dbpedia.org/sparql> {
        ?ski a dbo:SkiArea .
        ?ski rdfs:label ?s .
        ?ski geo:lat ?lat .
        ?ski geo:long ?lon .
        ?ski dbo:location+ ?country.
    }
    ?country a dbo:Country .  
    ?t a dbo:Town .
    ?t ns1:tempTypicalLow ?low . FILTER (?low < -5) .
    ?country ns1:hasTown ?t .
}
